---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda5-metadata-name-deployment
  # namespace: default
  labels:
    app: uda5-metadata-labels-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uda5-spec-labels-deployment # the same name at point 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: uda5-spec-labels-deployment # point 1
    spec:
      containers:
        - name: uda5-containers-name-service
          image: toantruong90/prj5:v1
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uda5-metadata-name-service
spec:
  type: NodePort
  selector:
    app: uda5-spec-labels-deployment  # the same name at point 1
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 31000
