version: 2.1
jobs:
  validate-docker:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
               chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  
  build-image:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t prj5:v1 .
            docker run -d -p 8000:80 prj5:v1
            docker image tag prj5:v1 toantruong90/prj5:v1
            docker image push toantruong90/prj5:v1
  
  deploy-image-eks:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/bin/kubectl
      - run:
          name: Config kubectl
          command: |
            aws eks update-kubeconfig --name eks-toantc-cluster-2
            aws eks --region us-east-1 update-kubeconfig --name eks-toantc-name
            kubectl get svc
      # - run:
      #     name: Deploy kubectl
      #     command: |
      #       kubectl apply -f k8s-uda5-deployment.yml

workflows:
  execute-prj5:
    jobs:
      - validate-docker
      - build-image:
          requires:
            - validate-docker
      - deploy-image-eks:
          requires:
            - build-image

